<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="">
        <form action="">
            <ul>
                <li>
                    <label for="username">Username</label>
                    <input type="text" name="username" require>
                </li>
                <li>
                    <label for="password">Password</label>
                    <input type="password" name="password" require>
                </li>
            </ul>
        </form>
    </div>
</body>
</html>